FROM rust-loongarch64-unknown-linux-musl

ENV CC_loongarch64_unknown_linux_musl=loongarch64-unknown-linux-musl-gcc \
    CARGO_TARGET_LOONGARCH64_UNKNOWN_LINUX_MUSL_LINKER=loongarch64-unknown-linux-musl-gcc
