name: Bug report
description: Create a report to help us improve
labels: [bug]
body:
  - type: markdown
    attributes:
      value: >
        **Thanks for filing a ðŸ› bug report ðŸ˜„!**

  - type: checkboxes
    attributes:
      label: Verification
      description: Please verify that you've followed these steps.
      options:
        - label: I searched for recent similar issues at https://github.com/rust-lang/rustup/issues?q=is%3Aissue+is%3Aopen%2Cclosed and found no duplicates.
          required: true
        - label: I am on the latest version of Rustup according to https://github.com/rust-lang/rustup/tags and am still able to reproduce my issue.
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: >
        A clear and concise description of what the bug is,
        including what currently happens and what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps
      description: The steps to reproduce the bug.
      placeholder: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    id: solutions
    attributes:
      label: Possible Solution(s)
      description: >
        Not obligatory, but suggest a fix/reason for the bug,
        or ideas how to implement the addition or change.

  - type: textarea
    id: notes
    attributes:
      label: Notes

  - type: textarea
    id: version
    attributes:
      label: Rustup version
      description: Output of `rustup --version`
      render: console
    validations:
      required: true

  - type: textarea
    id: toolchains
    attributes:
      label: Installed toolchains
      description: Output of `rustup show`
      render: console
    validations:
      required: true

  - type: textarea
    id: os
    attributes:
      label: OS version
      render: console
    validations:
      required: true
