name: Bug report
description: Create a report to help us improve
labels: [bug]
body:
  - type: markdown
    attributes:
      value: >
        **Thanks for filing a ðŸ› bug report ðŸ˜„!**

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: >
        A clear and concise description of what the bug is,
        including what currently happens and what you expected to happen.

  - type: textarea
    id: steps
    attributes:
      label: Steps
      description: The steps to reproduce the bug.
      placeholder: |
        1.
        2.
        3.

  - type: textarea
    id: solutions
    attributes:
      label: Possible Solution(s)
      description: >
        Not obligatory, but suggest a fix/reason for the bug,
        or ideas how to implement the addition or change.

  - type: textarea
    id: notes
    attributes:
      label: Notes

  - type: textarea
    id: version
    attributes:
      label: Rustup version
      description: Output of `rustup --version`
      render: console

  - type: textarea
    id: toolchains
    attributes:
      label: Installed toolchains
      description: Output of `rustup show`
      render: console
