name: Enhancement request
description: Suggest an enhancement for this project
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: >
        **Thanks for filing an 🙋 enhancement request 😄!**

  - type: textarea
    id: problem
    attributes:
      label: Problem you are trying to solve
      description: >
        A clear and concise description of the problem this enhancement request is trying to solve.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Solution you'd like
      description: >
        A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: >
        Any additional context or information you feel may be relevant to the issue.
