[alias]
dev-install = "run -- --no-modify-path -y"

[target.aarch64-pc-windows-msvc]
rustflags = ["-C", "link-arg=/STACK:8388608"]

[target.i686-pc-windows-gnu]
rustflags = ["-C", "link-arg=-Wl,--stack,8388608"]

[target.i686-pc-windows-msvc]
rustflags = ["-C", "link-arg=/STACK:8388608"]

[target.x86_64-pc-windows-gnu]
rustflags = ["-C", "link-arg=-Wl,--stack,8388608"]

[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "link-arg=/STACK:8388608"]
